/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'plex': ['"IBM Plex Sans"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'plex-mono': ['"IBM Plex Mono"', '"Courier New"', 'monospace'],
      },
      colors: {
        ink: {
          DEFAULT: 'var(--ps-ink)',
          muted: 'var(--ps-ink-muted)',
          subtle: 'var(--ps-ink-subtle)',
        },
        canvas: 'var(--ps-canvas)',
        'surface-1': 'var(--ps-surface-1)',
        'surface-2': 'var(--ps-surface-2)',
        hairline: 'var(--ps-hairline)',
        primary: {
          DEFAULT: '#0f62fe',
          hover: '#0050e6',
          pressed: '#002d9c',
        },
        'inverse-canvas': 'var(--ps-inverse-canvas)',
        'inverse-ink': {
          DEFAULT: 'var(--ps-inverse-ink)',
          muted: 'var(--ps-inverse-ink-muted)',
        },
        'footer-border': 'var(--ps-footer-border)',
        carbon: {
          'gray-100': '#161616',
          'gray-90': '#262626',
          'gray-80': '#393939',
          'gray-70': '#525252',
          'gray-60': '#6F6F6F',
          'gray-50': '#8D8D8D',
          'gray-40': '#A8A8A8',
          'gray-30': '#C6C6C6',
          'gray-20': '#E0E0E0',
          'gray-10': '#F4F4F4',
          'blue-80': '#002D9C',
          'blue-70': '#0043CE',
          'blue-60': '#0F62FE',
          'blue-50': '#4589FF',
          'blue-40': '#78A9FF',
          'teal-60': '#007D79',
          'teal-50': '#009D9A',
          'teal-40': '#08BDBA',
          'red-60': '#DA1E28',
          'red-50': '#FA4D56',
          'yellow-30': '#F1C21B',
          'green-50': '#24A148',
          'green-40': '#42BE65',
          'purple-50': '#A56EFF',
          'purple-60': '#8A3FFC',
        },
      },
      fontSize: {
        'display-xl': ['4.75rem', { lineHeight: '1.17', letterSpacing: '-0.5px', fontWeight: '300' }],
        'display-lg': ['3.75rem', { lineHeight: '1.17', letterSpacing: '-0.4px', fontWeight: '300' }],
        'display-md': ['2.625rem', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '300' }],
        'headline': ['2rem', { lineHeight: '1.25', letterSpacing: '0', fontWeight: '400' }],
        'card-title': ['1.5rem', { lineHeight: '1.33', letterSpacing: '0', fontWeight: '400' }],
        'subhead': ['1.25rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '400' }],
        'caption': ['0.75rem', { lineHeight: '1.33', letterSpacing: '0.32px', fontWeight: '400' }],
        'eyebrow': ['0.875rem', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '400' }],
      },
      spacing: {
        'carbon-01': '0.125rem',
        'carbon-02': '0.25rem',
        'carbon-03': '0.5rem',
        'carbon-04': '0.75rem',
        'carbon-05': '1rem',
        'carbon-06': '1.5rem',
        'carbon-07': '2rem',
        'carbon-08': '2.5rem',
        'carbon-09': '3rem',
        'carbon-10': '4rem',
        'carbon-11': '5rem',
        'carbon-12': '6rem',
        'carbon-13': '10rem',
        'section': '6rem',
      },
      transitionTimingFunction: {
        productive: 'cubic-bezier(0.2, 0, 0.38, 0.9)',
        expressive: 'cubic-bezier(0.4, 0.14, 0.3, 1)',
      },
      transitionDuration: {
        fast: '110ms',
        moderate: '150ms',
        slow: '240ms',
      },
    },
  },
  plugins: [],
}
